BestBankApp/Controllers/ClientsController.cs
using AutoMapper;
using BestBankApp.Models;
using BestBankApp.Repository;
using BestBankApp.Repository.Context;
using BestBankApp.Services.Helpers;
using BestBankApp.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Linq;

namespace BestBankApp.Controllers
{
    public class ClientsController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();
        private readonly IMapper _mapper;
        private readonly IRepository<Clients> _clients;
        private readonly IClientsService _clientsService;
        public ClientsController(IMapper mapper, IRepository<Clients> clients, IClientsService creditsService)
        {
            _mapper = mapper;
            _clients = clients;
            _clientsService = creditsService;
        }
        public ActionResult Index()
        {
            return View(_clients.All);
        }

        [HttpPost]
        public ActionResult Index(string surname)
        {
            try
            {
                if (surname == null || surname == "")
                    return RedirectToAction("Index");
                else
                    return View(_clients.All.Where(x => x.Surname == surname));
            }
            catch (Exception e)
            {
                return View(e);
            }
        }
        public ActionResult NewClient()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewClient(ClientPayload model)
        {
            SimpleResponse sr = new SimpleResponse();
            if (ModelState.IsValid)
            {
                sr = _clientsService.CreateClient(model);
                if (sr.ErrorCode == 0)
                    return RedirectToAction(nameof(Index));
                else
                    return View(sr);
            }
            else
            {
                sr.ErrorCode = 1;
                sr.Result = "Model is invalid!";
                return View(sr);
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                return View(_clientsService.ClientUpdate(id));
            }
            catch(Exception e)
            {
                return View(e);
            }            
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EditClientPayload model)
        {
            SimpleResponse sr = new SimpleResponse();
            if (ModelState.IsValid)
            {
                sr = _clientsService.ClientUpdate(id, model);
                if (sr.ErrorCode == 0)
                    return RedirectToAction(nameof(Index));
                else
                    return View(sr);
            }
            else
            {
                sr.ErrorCode = 1;
                sr.Result = "Model is invalid!";
                return View(sr);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                Clients client = db.CLIENTS.Find(id);
                db.CLIENTS.Remove(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(e);
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BestBankApp/Controllers/CreditApplicationsController.cs
using AutoMapper;
using BestBankApp.Models;
using BestBankApp.Repository;
using BestBankApp.Repository.Context;
using BestBankApp.Services.Helpers;
using BestBankApp.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace BestBankApp.Controllers
{
    public class CreditApplicationsController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();
        private readonly IMapper _mapper;
        private readonly IRepository<Clients> _clients;
        private readonly IRepository<Credits> _credits;
        private readonly ICreditsService _creditsService;
        public CreditApplicationsController(IMapper mapper, IRepository<Clients> clients, IRepository<Credits> credits, ICreditsService creditsService)
        {
            _mapper = mapper;
            _clients = clients;
            _credits = credits;
            _creditsService = creditsService;
        }
        public ActionResult Index()
        {
            try
            {
                return View(_credits.AllQuery.Include(x => x.CLIENTS));
            }
            catch (Exception e)
            {
                return View(e);
            }
        }

        [HttpPost]
        public ActionResult Index(string result)
        {
            try
            {
                if (result == null) return RedirectToAction("Index");
                return View(_creditsService.CreditAppliesList(result));
            }
            catch (Exception e)
            {
                return View(e);
            }
                
        }
      
        public ActionResult CreditApply(int id)
        {
            try
            {
                var client = _clients.AllQuery.Single(x => x.Id == id);
                CreditApplyPayload credit_apply = _mapper.Map<Clients, CreditApplyPayload>(client);
                return View(credit_apply);

            }catch(Exception e)
            {
                return View(e);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreditApply(CreditApplyPayload model)
        {
            SimpleResponse sr = new SimpleResponse();
            if (ModelState.IsValid)
            {
                sr = _creditsService.CheckApply(model);
                if (sr.ErrorCode == 0)
                    return RedirectToAction(nameof(Index));
                else
                    return View(sr);
            }
            else
            {
                sr.ErrorCode = 1;
                sr.Result = "Model is invalid!";
                return View(sr);
            }
        }

    }
}

BestBankApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BestBankApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Clients" asp-action="Index">Best Bank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditApplications" asp-action="Index">Credit applications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BestBankApp - <a asp-area="" asp-controller="Clients" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>